# Generated by Django 4.2.5 on 2023-09-29 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Message',
        ),
    ]
