# Generated by Django 4.2.5 on 2023-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0002_rename_restaurant_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='contenu',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
