# Generated by Django 4.2.5 on 2023-09-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napi', '0003_remove_message_message_message_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
